trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    npm install
    npm run build
  
  displayName: '🌐 Instalar dependências e build'

- task: AzureStaticWebApp@0
  displayName: '🚀 Deploy para Azure Static Web App'
  inputs:
    app_location: '/'
    api_location: ''
    output_location: 'dist'
    azure_static_web_apps_api_token: $(AZURE_SWA_API_TOKEN)
